### ISSUE TITLE
CSS Breaking in all auto-generated pages.

### ISSUE THREAD

**Issue by aero31aero** [crux-bphc/crux-bphc.github.io#5]
Go to [this page](https://crux-bphc.github.io/docs/members.html) on Firefox/Chrome. You'll be greeted with this: 
![image](https://cloud.githubusercontent.com/assets/8033238/24268175/bf3a198a-1032-11e7-83d6-f3ed7beecd8b.png)

The error is in the file: `/src/maker/template.html`

**Comment by hereisdx** [comment]
Closing as the website has been entirely revamped.
