### ISSUE TITLE
Blog Post Feed Page Generator

### ISSUE THREAD

**Issue by aero31aero** [crux-bphc/crux-bphc.github.io#7]
1. Copy the file `src/maker/member-list-maker.py` as `src/maker/blog-feed-maker.py`.
2. Modify it to pick up posts from `/src/docs/blog` and to generate the file `src/docs/blog.md` as output.
3. Create random test files like `src/docs/blog/test.md`.
4. Here comes the tricky part. Blog Posts need to display the author and other such information. Use a YAML parser to extract that information from the post.
5. Edit the testing posts to have YAML formatted variables in it like Author,etc.
6. Display each blog post as a Title followed by Author Name and Publishing Date in the next line.
7. Create a PR and then we'll fix minor issues back and forth.
8. Would be merged to upstream.

**Comment by nsurampu** [comment]
Could you elaborate a bit on the way the original post is being created? Is it an md file like the profile ones which need to be PRed or something else?

**Comment by hereisdx** [comment]
Closing as the website has been entirely revamped.
